using System;
using System.Collections.Generic;
using System.Linq;
using Emby.Plugin.RdZurg.Library;
using Xunit;

namespace Emby.Plugin.RdZurg.Tests;

/// <summary>
/// Holds the vendored parser to the two recorded references the Jellyfin plugins were validated against.
/// </summary>
/// <remarks>
/// <para>
/// <c>episode-corpus.tsv.gz</c> is the same fixture the Jellyfin family uses: real release and file names from
/// DMM's availability tables, labelled independently of any parser (2,041 films, 9,028 episodes).
/// </para>
/// <para>
/// <c>parse-golden.tsv.gz</c> records what the Jellyfin plugin's own parsing (Jellyfin.Naming 12.0.0) made of the
/// same names and of the two library fixtures: a film's title and year, and an episode's series name and numbers.
/// Those decide an item's folder here, and a folder is an Emby item's identity. It is generated by
/// <c>tools/parse-golden</c>.
/// </para>
/// </remarks>
public class ParserCorpusTests
{
    private readonly ReleaseNames _names = new();

    [Fact]
    public void DoesNotReadFilmsAsEpisodes()
    {
        var rows = Fixture.Tsv("episode-corpus.tsv.gz").Where(r => r[2] == "-").ToList();
        Assert.Equal(2041, rows.Count);
        AssertEpisodes(rows);
    }

    [Fact]
    public void KeepsEveryEpisodeNumber()
    {
        var rows = Fixture.Tsv("episode-corpus.tsv.gz").Where(r => r[2] != "-").ToList();
        Assert.Equal(9028, rows.Count);
        AssertEpisodes(rows);
    }

    [Fact]
    public void ReadsFilmTitlesAndYearsAsJellyfinDid()
    {
        var rows = Fixture.Tsv("parse-golden.tsv.gz").Where(r => r[0] == "movie").ToList();
        Assert.Equal(2212, rows.Count);

        var wrong = new List<string>();
        foreach (var r in rows)
        {
            var (name, year) = ReleaseNames.MovieTitle(r[3], r[2]);
            var read = name + " | " + (year?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "-");
            var expected = r[4] + " | " + r[5];
            if (read != expected)
            {
                wrong.Add($"{expected}  read as  {read}  <=  {r[3]}");
            }
        }

        Assert.True(wrong.Count == 0, $"{wrong.Count} of {rows.Count} differ:{Environment.NewLine}{string.Join(Environment.NewLine, wrong.Take(40))}");
    }

    /// <summary>
    /// No name in the corpus reads a resolution such as <c>1920x1080</c> as its year. The film-year assertion above
    /// never saw the shape: the two corpus rows carrying it are series, whose folder is named without a year, so
    /// every name in the corpus is read here as a film would be - the release and the file alike.
    /// </summary>
    [Fact]
    public void NeverReadsAResolutionAsAYear()
    {
        var names = Fixture.Tsv("episode-corpus.tsv.gz").SelectMany(r => new[] { r[0], System.IO.Path.GetFileNameWithoutExtension(r[1]) })
            .Concat(Fixture.Tsv("parse-golden.tsv.gz").SelectMany(r => new[] { r[2], System.IO.Path.GetFileNameWithoutExtension(r[3]) }))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        var wrong = new List<string>();
        foreach (var name in names)
        {
            var year = ReleaseNames.ParseName(ReleaseNames.Humanise(name)).Year;
            if (year is int value && !System.Text.RegularExpressions.Regex.IsMatch(
                    name,
                    FormattableString.Invariant($"(?<![0-9]){value}(?![0-9]|[xX][0-9]{{3,4}}(?![0-9]))")))
            {
                wrong.Add(FormattableString.Invariant($"{value}  <=  {name}"));
            }
        }

        Assert.True(names.Count > 11000, $"only {names.Count} names");
        Assert.True(wrong.Count == 0, $"{wrong.Count} read a resolution as a year:{Environment.NewLine}{string.Join(Environment.NewLine, wrong.Take(20))}");
    }

    [Fact]
    public void ReadsSeriesNamesAsJellyfinDidOnTheRealLibrary()
    {
        // The library fixtures came from a live account and were checked in Jellyfin; on the corpus this parser
        // deliberately differs (Jellyfin kept episode titles and read "HD" or "DUAL" as a series), which
        // SeriesTitlesAreClean and SeriesTitlesAreStable cover instead.
        var rows = Fixture.Tsv("parse-golden.tsv.gz").Where(r => r[0] == "series" && r[1] != "corpus").ToList();
        Assert.Equal(163, rows.Count);
        var wrong = rows.Select(r => (Row: r, Read: Describe(_names.ParseEpisode(r[2], r[3]))))
            .Where(x => x.Read != x.Row[4] + " | " + x.Row[5])
            .Select(x => $"{x.Row[4]} | {x.Row[5]}  read as  {x.Read}  <=  {x.Row[3]}")
            .ToList();
        Assert.True(wrong.Count == 0, string.Join(Environment.NewLine, wrong.Take(20)));
    }

    [Fact]
    public void SeriesTitlesAreClean()
    {
        var bad = new List<string>();
        foreach (var r in Fixture.Tsv("parse-golden.tsv.gz").Where(r => r[0] == "series"))
        {
            var episode = _names.ParseEpisode(r[2], r[3]);
            if (episode is null)
            {
                bad.Add("no episode: " + r[3]);
                continue;
            }

            var title = ReleaseNames.SeriesTitle(episode);

            // "3x3 Eyes" is the show's name, not a marker.
            var markerFree = title.Replace("3x3", string.Empty, StringComparison.OrdinalIgnoreCase);
            if (string.IsNullOrWhiteSpace(title) || title != title.Trim() || _marker.IsMatch(markerFree) || _tags.IsMatch(title)
                || title.Count(c => c == '(') != title.Count(c => c == ')') || title.Count(c => c == '[') != title.Count(c => c == ']'))
            {
                bad.Add($"{title}  <=  {r[2]} | {r[3]}");
            }
        }

        Assert.True(bad.Count == 0, $"{bad.Count} unclean:{Environment.NewLine}{string.Join(Environment.NewLine, bad.Take(40))}");
    }

    /// <summary>
    /// A series title names the series folder, and a folder is an Emby item's identity: changing how a release
    /// parses moves every file under it and drops the watch history of anything unmatched. So every title is
    /// pinned. Set <c>UPDATE_SERIES_SNAPSHOT=1</c> to rewrite the snapshot after a deliberate change, and review
    /// the diff as a migration.
    /// </summary>
    [Fact]
    public void SeriesTitlesAreStable()
    {
        var current = Fixture.Tsv("parse-golden.tsv.gz").Where(r => r[0] == "series")
            .Select(r => string.Join('\t', r[2], r[3], Describe(_names.ParseEpisode(r[2], r[3]))))
            .ToList();

        if (Environment.GetEnvironmentVariable("UPDATE_SERIES_SNAPSHOT") == "1")
        {
            Fixture.WriteTsv("series-titles.tsv.gz", "# release\tfile\tseries | numbers  (this plugin's parser; see SeriesTitlesAreStable)", current);
        }

        var pinned = Fixture.Tsv("series-titles.tsv.gz").Select(r => string.Join('\t', r)).ToList();
        Assert.Equal(pinned.Count, current.Count);
        var moved = pinned.Zip(current).Where(p => p.First != p.Second).Select(p => $"{p.First}{Environment.NewLine}  now {p.Second.Split('\t')[2]}").ToList();
        Assert.True(moved.Count == 0, $"{moved.Count} series titles moved:{Environment.NewLine}{string.Join(Environment.NewLine, moved.Take(20))}");
    }

    private static readonly System.Text.RegularExpressions.Regex _marker = new(@"\b[sS]?[0-9]{1,4}[xX][0-9]{1,4}\b|\b[sS][0-9]{1,3}[eE][0-9]{1,4}\b|\bSeason\s*[0-9]", System.Text.RegularExpressions.RegexOptions.IgnoreCase);

    private static readonly System.Text.RegularExpressions.Regex _tags = new(@"\b(?:1080p|720p|2160p|x264|x265|h264|h265|web-dl|webrip|bluray|bdrip|hdtv|dvdrip)\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase);

    private static string Describe(EpisodeName? episode)
        => episode is null ? "-" : SeriesFolderName(episode) + " | " + Numbers(episode);

    private static string SeriesFolderName(EpisodeName episode) => ReleaseNames.SeriesTitle(episode);

    private static string Numbers(EpisodeName e)
        => FormattableString.Invariant($"S{e.SeasonNumber}E{e.EpisodeNumber}") + (e.EndingEpisodeNumber is int end ? FormattableString.Invariant($"-E{end}") : string.Empty);

    private void AssertEpisodes(IReadOnlyCollection<string[]> rows)
    {
        var wrong = new List<string>();
        foreach (var r in rows)
        {
            var parsed = _names.ParseEpisode(r[0], r[1]);
            var read = parsed is null ? "-" : FormattableString.Invariant($"S{parsed.SeasonNumber}E{parsed.EpisodeNumber}");
            if (read != r[2])
            {
                wrong.Add($"{r[2]} read as {read}: {r[0]} | {r[1]}");
            }
        }

        Assert.True(wrong.Count == 0, $"{wrong.Count} of {rows.Count} misread:{Environment.NewLine}{string.Join(Environment.NewLine, wrong.Take(60))}");
    }
}
